// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi1fsyUH5TdXNPxITis6X3RsrprUWK5-c',
    appId: '1:867718839176:web:4dabf86af3ef290bd2d83d',
    messagingSenderId: '867718839176',
    projectId: 'ishow-e8d16',
    authDomain: 'ishow-e8d16.firebaseapp.com',
    storageBucket: 'ishow-e8d16.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk0MXK8goVHyGap-ujYzGl7bdJQAVTBTM',
    appId: '1:867718839176:android:55b0c8d35ead9091d2d83d',
    messagingSenderId: '867718839176',
    projectId: 'ishow-e8d16',
    storageBucket: 'ishow-e8d16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKiYaPbIBZ3Xo2PDSXfcwUhoxrrhqadqk',
    appId: '1:867718839176:ios:11811320af24032ad2d83d',
    messagingSenderId: '867718839176',
    projectId: 'ishow-e8d16',
    storageBucket: 'ishow-e8d16.appspot.com',
    iosBundleId: 'com.example.ishow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKiYaPbIBZ3Xo2PDSXfcwUhoxrrhqadqk',
    appId: '1:867718839176:ios:11811320af24032ad2d83d',
    messagingSenderId: '867718839176',
    projectId: 'ishow-e8d16',
    storageBucket: 'ishow-e8d16.appspot.com',
    iosBundleId: 'com.example.ishow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi1fsyUH5TdXNPxITis6X3RsrprUWK5-c',
    appId: '1:867718839176:web:fc019e5a3ac5c652d2d83d',
    messagingSenderId: '867718839176',
    projectId: 'ishow-e8d16',
    authDomain: 'ishow-e8d16.firebaseapp.com',
    storageBucket: 'ishow-e8d16.appspot.com',
  );
}
